import type { LiteracyUnit } from "./corpus.ts";

const YOUTH = "oecd-infe-youth";
const DIGITAL = "eu-oecd-digital";
const BCEAO = "bceao";
const BRVM = "brvm";

export const LITERACY_UNITS_EN: LiteracyUnit[] = [
  // ── Earn ────────────────────────────────────────────────────────────────
  {
    id: "money-goals", area: "earn", locale: "en", title: "Give your money a job",
    summary: "Money is a tool. Deciding what you want it to do this month, this year and in five years is the first financial skill.",
    points: [
      "Write each goal with an amount and a date: “150,000 F for a laptop by June”.",
      "Sort goals by horizon: short (weeks), medium (months), long (years).",
      "A goal with a monthly amount becomes a habit; without one it stays a wish.",
      "Review your goals when your income or your life changes.",
    ],
    example: "A laptop at 150,000 F in 10 months means 15,000 F a month. If that is too much, change the date or the model, not the habit of saving.",
    watchOut: "Goals copied from social media belong to someone else’s life. Start from your own.",
    aliases: ["goal", "objective", "plan", "dream", "target", "priorities"], sources: [YOUTH],
  },
  {
    id: "first-income", area: "earn", locale: "en", title: "Your first income",
    summary: "The first months of income set habits that last for years. Decide the shares before the money arrives.",
    points: [
      "Before payday, decide three shares: living, saving, family or giving.",
      "Save first, the day you are paid, even a small amount.",
      "Keep the same lifestyle for the first three months, then raise it slowly.",
      "Receive income on an account in your own name: the history helps later to rent, borrow or prove income.",
    ],
    example: "First pay of 120,000 F: 12,000 F saved on day one (10 %), 20,000 F for family, 88,000 F to live. The 10 % is a starting point, not a law.",
    watchOut: "Spending everything “because it is the first” usually becomes the rule.",
    aliases: ["salary", "first job", "stipend", "internship", "allowance", "payday", "pay"], sources: [YOUTH],
  },
  {
    id: "irregular-income", area: "earn", locale: "en", title: "Hustle and irregular income",
    summary: "Freelance, trade, gigs and side hustles pay unevenly. The skill is turning uneven income into a steady life.",
    points: [
      "Compute your average month over the last six months, then budget on a low month, not the best one.",
      "In good months fill a buffer; in weak months pay yourself from it.",
      "Keep hustle money and personal money in two separate wallets or accounts.",
      "Set aside what the activity needs (stock, data, fees, taxes) before counting profit.",
    ],
    example: "Six months earn 40,000, 90,000, 60,000, 30,000, 110,000 and 70,000 F: 400,000 F in total, about 66,700 F on average, 30,000 F at worst. Plan living costs near 50,000 F and send the surplus of good months to the buffer.",
    watchOut: "A great month is not a new salary.",
    aliases: ["freelance", "gig", "side hustle", "business", "trade", "commission", "seasonal", "variable income"], sources: [YOUTH],
  },
  {
    id: "family-support", area: "earn", locale: "en", title: "Supporting family without sinking",
    summary: "Helping family is a value and a real budget line. Planned, it lasts; improvised, it drains you and helps less.",
    points: [
      "Plan family support like rent: a monthly amount you can sustain, said clearly.",
      "Build your own emergency reserve first; a broke helper helps nobody.",
      "Prefer help that builds: school fees, a tool, health cover.",
      "Tell emergencies from habits, and decide in advance what counts as an emergency.",
    ],
    example: "Income 150,000 F: a fixed 20,000 F for family each month plus a 5,000 F “family emergencies” pot is easier to hold than answering every request from what is left.",
    watchOut: "Borrowing in order to give creates two problems: yours and theirs.",
    aliases: ["black tax", "parents", "relatives", "siblings", "requests", "solidarity", "obligation", "help family"], sources: [YOUTH],
  },
  {
    id: "lifestyle-pressure", area: "earn", locale: "en", title: "Needs, wants and social pressure",
    summary: "Needs keep you living and working, wants make life pleasant. Both are legitimate, in that order.",
    points: [
      "Lifestyle creep: every raise disappears if spending rises at the same speed.",
      "Wait 24 hours before an impulse buy, 30 days for a big one. Most urges pass.",
      "Measure a price in hours or months of work, not against what friends own.",
      "Keep a small fun budget: a plan with no pleasure never lasts.",
    ],
    example: "A 300,000 F phone on an income of 100,000 F is three months of work. “Would I work three months for this?” is a clearer question than “can I afford the instalment?”.",
    watchOut: "Buying to look successful delays becoming it.",
    aliases: ["impulse", "peer pressure", "status", "phone", "fashion", "show off", "lifestyle inflation"], sources: [YOUTH],
  },
  // ── Spend ───────────────────────────────────────────────────────────────
  {
    id: "budget-basics", area: "spend", locale: "en", title: "A budget in four lines",
    summary: "A budget gives every franc a job before the month starts: income minus savings, fixed costs and flexible spending equals zero.",
    points: [
      "Fixed costs: rent, transport, school, subscriptions. Flexible: food, outings, clothes, data.",
      "Write the budget before the month starts and adjust it during the month.",
      "When one line rises, another must fall. Savings are the last line to touch.",
      "A budget is a plan, not a punishment: include money for fun.",
    ],
    example: "Income 100,000 F: 10,000 F savings, 45,000 F fixed, 45,000 F flexible. If transport rises by 5,000 F, take it from flexible spending, not from savings.",
    watchOut: "A budget you never look at again is a wish list.",
    aliases: ["budget", "plan spending", "monthly plan", "expenses", "how to budget"], sources: [YOUTH],
  },
  {
    id: "budget-methods", area: "spend", locale: "en", title: "50/30/20, envelopes and pots",
    summary: "Several simple methods exist. The best one is the one you still use after three months.",
    points: [
      "50/30/20: about half for needs, 30 % for wants, 20 % for savings and debt.",
      "On a low income, needs can take 70 %. Keep the order, change the numbers.",
      "Envelopes or wallet pots: one per category; when a pot is empty, that category stops.",
      "Zero-based: plan every franc each month. It suits irregular income.",
    ],
    example: "80,000 F split 70/20/10 gives 56,000 F for needs, 16,000 F for wants and 8,000 F for savings.",
    watchOut: "Percentages are a guide. Rent that takes half your income is a housing question, not a budgeting failure.",
    aliases: ["50 30 20", "envelope", "pots", "zero based", "rule", "method"], sources: [YOUTH],
  },
  {
    id: "tracking-spending", area: "spend", locale: "en", title: "Where the money really goes",
    summary: "Recording every expense for one month shows two or three leaks that nobody notices otherwise.",
    points: [
      "Small daily costs add up: 500 F a day is 15,000 F a month and 182,500 F a year.",
      "Usual leaks: data bundles, snacks, taxis, withdrawal fees, betting.",
      "Track by category and look once a week, not once a year.",
      "Change one thing at a time; three changes at once rarely hold.",
    ],
    example: "Three cash withdrawals a week at 300 F in fees cost about 3,900 F a month. One planned withdrawal a week cuts that by two thirds.",
    watchOut: "Tracking is for seeing clearly, not for feeling guilty.",
    aliases: ["track", "record", "leaks", "small expenses", "data bundle", "fees", "where does my money go"], sources: [YOUTH],
  },
  {
    id: "inflation", area: "spend", locale: "en", title: "Inflation: why prices rise",
    summary: "Inflation is the general rise of prices. The same money buys less over time.",
    points: [
      "Money sleeping at 0 % loses purchasing power every year.",
      "What counts is the real return: the interest rate minus inflation.",
      "Income has to follow prices: renegotiate pay and prices regularly.",
      "For a known increase on something durable you need, buying earlier can be rational. Stockpiling out of fear is not.",
    ],
    example: "With 3 % inflation, a basket at 100,000 F costs about 103,000 F next year. Savings at 2 % grew to 102,000 F: the number went up, the purchasing power went down.",
    watchOut: "A “guaranteed” product that pays less than inflation guarantees a slow loss.",
    aliases: ["prices", "cost of living", "purchasing power", "expensive", "real return"], sources: [YOUTH],
  },
  {
    id: "big-moments", area: "spend", locale: "en", title: "Planning the big moments",
    summary: "School fees, rent advances, feasts, weddings, funerals and travel are predictable. What is predictable can be saved for.",
    points: [
      "Put every big expense of the year on a calendar with its amount.",
      "Divide the amount by the months left and save that each month.",
      "Keep these pots separate from the emergency fund.",
      "Fix your ceiling for social events before the invitation arrives.",
    ],
    example: "School fees of 90,000 F due in October: saving from January takes 10,000 F a month for nine months. Starting in July takes 30,000 F a month.",
    watchOut: "An expense that returns every year is not an emergency.",
    aliases: ["school fees", "rent advance", "wedding", "funeral", "feast", "tabaski", "christmas", "travel", "sinking fund", "planned expense"], sources: [YOUTH],
  },
  // ── Digital money ───────────────────────────────────────────────────────
  {
    id: "mobile-money", area: "digital", locale: "en", title: "Mobile money, properly used",
    summary: "A mobile wallet is an account on your SIM, run by an operator under central-bank rules. The money is yours, not the agent’s.",
    points: [
      "Register the wallet in your own name with your ID: higher limits and a way to recover it.",
      "Know the fee grid. Deposits are usually free; withdrawals and transfers to other networks usually cost. Check your operator’s current grid.",
      "Keep every confirmation message: it is your receipt.",
      "A balance kept in the wallet for savings should sit in a separate wallet or account from daily money.",
    ],
    example: "Paying a merchant from the wallet often costs less than withdrawing cash first. Compare the two fees before your next purchase.",
    watchOut: "Never give your PIN, not even to an agent or to “customer service”. No real agent needs it.",
    aliases: ["wallet", "orange money", "wave", "moov", "mtn momo", "m-pesa", "agent", "withdrawal", "fees", "kyc", "limits"], sources: [DIGITAL, BCEAO],
  },
  {
    id: "accounts", area: "digital", locale: "en", title: "Bank, microfinance or digital account",
    summary: "Accounts differ in cost, access and safety. Choosing one is a comparison, not a matter of prestige.",
    points: [
      "Compare four things: monthly fees, minimum balance, access (agents, branches, app) and what the account earns.",
      "Banks and licensed microfinance institutions are supervised. Ask whether an institution is licensed before depositing.",
      "An account history in your name helps you rent, borrow and prove income.",
      "Use the wallet for daily flows and an account you do not carry in your pocket for savings.",
    ],
    example: "An account with 1,000 F of monthly fees costs 12,000 F a year. If it pays nothing and you never use the branch, a cheaper option does the same job.",
    watchOut: "An app that takes deposits without a licence is not a bank, whatever its design.",
    aliases: ["bank", "microfinance", "neobank", "savings account", "open account", "fees", "licensed"], sources: [DIGITAL, BCEAO],
  },
  {
    id: "digital-safety", area: "digital", locale: "en", title: "Protecting your phone money",
    summary: "Most digital theft does not break technology. It convinces the owner to hand over the key.",
    points: [
      "A secret PIN, different from your birth date, never shared, never typed on a link you received.",
      "SIM swap: if your line dies for no reason, call the operator at once and block the wallet.",
      "Messages about a prize, a blocked account or a “transfer by mistake” push you to act fast. Slow down and check through the official number.",
      "Lock your phone, update your apps and install only from the official store.",
    ],
    example: "“I sent you 25,000 F by mistake, please send it back.” Check your real balance first. If nothing arrived, it is a scam. If money did arrive, ask the operator to reverse it rather than sending it yourself.",
    watchOut: "Urgency is the scammer’s main tool. Any real problem survives a ten-minute check.",
    aliases: ["pin", "sim swap", "phishing", "hack", "fake agent", "otp", "security", "stolen phone", "fraud"], sources: [DIGITAL],
  },
  {
    id: "scams-ponzi", area: "digital", locale: "en", title: "Scams and pyramid schemes",
    summary: "A pyramid scheme pays early members with newcomers’ money. It collapses when recruitment slows, every time.",
    points: [
      "Red flags: guaranteed high returns, pressure to recruit, urgency, no clear product, no licence.",
      "Screenshots of gains and testimonials in WhatsApp or Telegram groups prove nothing.",
      "Ask two questions: who is licensed to take this money, and where does the profit come from?",
      "A friend or relative who invites you is usually a victim too, not a guarantee.",
    ],
    example: "“Deposit 50,000 F, receive 100,000 F in 30 days” is a return of 100 % a month. No real business sustains that. Someone’s deposit pays it, until yours is the one that pays.",
    watchOut: "Getting paid once is part of the trick: it is what makes you bring more money and more people.",
    aliases: ["ponzi", "pyramid", "mlm", "network marketing", "double your money", "investment group", "telegram", "whatsapp group", "arnaque"], sources: [DIGITAL, YOUTH],
  },
  {
    id: "betting", area: "digital", locale: "en", title: "Betting is not an income",
    summary: "Bookmakers build a margin into every odd. On average players lose, and the more they play the surer the loss.",
    points: [
      "A win is remembered and ten losses are forgotten. Record bets like any expense to see the truth.",
      "Betting to recover losses or to pay a debt is the danger signal.",
      "If you bet for fun, fix a monthly entertainment amount and never borrow for it.",
      "“Sure tips” and paid prediction groups earn from subscribers, not from winning.",
    ],
    example: "1,000 F a day in bets is 30,000 F a month. Because of the operator’s margin, the expected result over a year is a loss, not a salary. The same 30,000 F saved each month is 360,000 F in a year.",
    watchOut: "If you cannot stop, talk to someone you trust. It is a known addiction, not a weakness of character.",
    aliases: ["bet", "sports betting", "gambling", "odds", "casino", "lottery", "tips", "pari"], sources: [YOUTH],
  },
  {
    id: "remittances-fx", area: "digital", locale: "en", title: "Sending money and exchange rates",
    summary: "A transfer costs two things: the visible fee and the exchange-rate margin. Compare what arrives, not the fee.",
    points: [
      "The CFA franc (XOF) has a fixed parity with the euro: 1 euro = 655.957 F CFA. Other currencies move every day.",
      "Digital services are often cheaper than cash counters. Compare for your corridor.",
      "For regular support, fewer and larger transfers usually cost less than many small ones.",
      "Use only licensed services and keep the reference of every transfer.",
    ],
    example: "Two services send 100 euros. A charges a 2 euro fee at 650 F per euro: 65,000 F arrive for 102 euros paid, about 637 F per euro. B charges no fee at 640 F: 64,000 F arrive for 100 euros paid, 640 F per euro. B is cheaper.",
    watchOut: "“Zero fees” often hides a weaker exchange rate.",
    aliases: ["transfer", "diaspora", "send money", "receive money", "exchange rate", "euro", "dollar", "currency", "western union", "fx"], sources: [DIGITAL, BCEAO],
  },
  // ── Save and grow ───────────────────────────────────────────────────────
  {
    id: "emergency-fund", area: "grow", locale: "en", title: "Pay yourself first, build a cushion",
    summary: "Savings come out the day income arrives, not from what is left. The first goal is a cushion for emergencies.",
    points: [
      "Automate if you can: a standing transfer on payday.",
      "First target: one month of essential expenses. Then three to six.",
      "Keep it reachable but not in your pocket: a separate wallet or account.",
      "Use it for real emergencies only (health, lost income, urgent repair), then rebuild it.",
    ],
    example: "Essential expenses of 60,000 F a month: saving 10,000 F a month builds the first month of cushion in six months and three months (180,000 F) in eighteen.",
    watchOut: "A sale is not an emergency.",
    aliases: ["savings", "emergency", "cushion", "reserve", "rainy day", "save", "pay yourself first"], sources: [YOUTH],
  },
  {
    id: "where-to-save", area: "grow", locale: "en", title: "Where to keep savings",
    summary: "Judge every place on four criteria: safety, access, cost and what it earns.",
    points: [
      "Cash at home is free and instant, but exposed to theft, fire and temptation.",
      "Wallets and bank or microfinance savings accounts are safer and traceable. Some pay interest or let you lock money.",
      "Savings groups (tontines, village savings groups) add discipline and solidarity. Their safety depends on known members and written rules.",
      "Match the place to the purpose: instant access for emergencies, locked for goals.",
    ],
    example: "Daily money in the wallet, the emergency fund in a separate savings account, next year’s goal in a locked product or in a group whose payout date matches the goal.",
    watchOut: "The safest place is the one where you cannot reach the money by reflex.",
    aliases: ["tontine", "savings group", "vsla", "cash at home", "savings account", "lock", "term deposit", "where to save"], sources: [YOUTH],
  },
  {
    id: "compound-interest", area: "grow", locale: "en", title: "Compound interest: time is the engine",
    summary: "Simple interest is paid on the capital only. Compound interest is paid on the capital plus past interest, so growth accelerates.",
    points: [
      "The earlier you start, the more of the work time does for you.",
      "Rule of 72: years to double ≈ 72 ÷ annual rate.",
      "Regular small amounts beat a large amount started late.",
      "Compounding also works against you on debt.",
    ],
    example: "100,000 F at 6 % a year: after 5 years, 130,000 F with simple interest and about 133,800 F compounded. After 20 years, 220,000 F simple and about 320,700 F compounded. At 6 %, money doubles in about 12 years.",
    watchOut: "Compounding needs a realistic rate. A promised 10 % a month is not compounding, it is a scam.",
    aliases: ["interest", "compound", "simple interest", "rule of 72", "growth", "double money", "rate"], sources: [YOUTH],
  },
  {
    id: "risk-return", area: "grow", locale: "en", title: "Risk, return and diversification",
    summary: "A higher possible return always comes with a higher risk. “High and guaranteed” does not exist.",
    points: [
      "Three questions before investing: can I lose capital, when can I get my money back, what does it cost?",
      "Diversify: several assets, not all your eggs in one basket.",
      "Match the investment to the horizon: money needed within two years should not be at risk.",
      "Understand it or leave it. Complexity is not a sign of quality.",
    ],
    example: "300,000 F lent entirely to one friend’s business is one risk. The same amount split between a savings account, a term deposit and a small stake in that business survives one failure.",
    watchOut: "Past performance is a history, not a promise.",
    aliases: ["risk", "return", "diversify", "liquidity", "horizon", "safe investment", "guaranteed"], sources: [YOUTH],
  },
  {
    id: "investing-basics", area: "grow", locale: "en", title: "Investing: the main families",
    summary: "Investing means buying something expected to earn or gain value over years. Each family has its own risk and exit.",
    points: [
      "Term deposits: low risk, modest return, fixed duration.",
      "Bonds and treasury bills: you lend to a state or a company in exchange for interest.",
      "Shares: you own part of a company and its value moves. In the WAEMU they trade on the regional exchange, the BRVM, through licensed brokers.",
      "Funds pool many investors across many assets. Land and your own business are investments too, with low liquidity and their own risks.",
    ],
    example: "Before any investment, write three lines: what I am buying, how it earns money, how I get out. If one line stays empty, you are not ready for that one yet.",
    watchOut: "This is education. WiseMoney recommends no product. Check that any intermediary is licensed.",
    aliases: ["invest", "shares", "stocks", "bonds", "treasury bills", "brvm", "fund", "land", "stock exchange", "broker"], sources: [YOUTH, BRVM],
  },
  {
    id: "crypto-forex", area: "grow", locale: "en", title: "Crypto and trading: a reality check",
    summary: "Cryptoassets and short-term trading are speculation, not saving. Prices can halve in weeks and most retail traders lose money.",
    points: [
      "Cryptoassets are highly volatile and are not legal tender in most countries.",
      "Forex, crypto and “signals” trading reward the platform and the trainer more surely than the trader.",
      "“Academies” and account managers promising monthly returns are a common scam format.",
      "If you still want exposure: only money you can lose completely, after the emergency fund, never borrowed.",
    ],
    example: "“Send 100,000 F, our trader returns 30 % a month” means multiplying money by about 23 in a year. No fund in the world does that. The promise itself is the proof of fraud.",
    watchOut: "Lost or stolen crypto is rarely recoverable, and there is usually nobody to complain to.",
    aliases: ["bitcoin", "crypto", "forex", "trading", "signals", "binance", "usdt", "trader", "academy", "nft"], sources: [DIGITAL],
  },
  // ── Borrow ──────────────────────────────────────────────────────────────
  {
    id: "credit-basics", area: "borrow", locale: "en", title: "How credit works",
    summary: "Three numbers define a loan: the capital borrowed, the interest rate and the duration. Fees and insurance come on top.",
    points: [
      "Each instalment repays some capital and some interest.",
      "A longer duration means smaller instalments and more total interest.",
      "Borrow for something that lasts longer than the loan.",
      "Ask for the repayment schedule before signing, and keep it.",
    ],
    example: "200,000 F over 12 months at 1.5 % a month on the initial capital: 3,000 F of interest a month, 36,000 F in total. You repay 236,000 F, about 19,700 F a month.",
    watchOut: "The instalment tells you whether you can pay. The total tells you what it costs.",
    aliases: ["loan", "credit", "borrow", "instalment", "interest rate", "repayment", "schedule"], sources: [YOUTH],
  },
  {
    id: "true-cost-credit", area: "borrow", locale: "en", title: "The true cost of a loan",
    summary: "The real price of a loan is everything you pay beyond the capital, expressed per year.",
    points: [
      "Add it all: interest, application fees, insurance, compulsory savings.",
      "The effective annual rate (TEG, APR) puts everything into one yearly percentage. It is the number to compare.",
      "A “small” rate per week or per month is a large rate per year.",
      "In the WAEMU the law sets a maximum rate, the usury ceiling. Licensed lenders must respect it and state their rate.",
    ],
    example: "Borrow 20,000 F and repay 22,000 F after 30 days: 10 % for one month. Repeated all year, that is 120 % a year before any compounding.",
    watchOut: "A lender who will not state the annual rate is telling you something.",
    aliases: ["apr", "teg", "taeg", "cost of credit", "fees", "usury", "interest per month", "expensive loan"], sources: [YOUTH, BCEAO],
  },
  {
    id: "digital-loans", area: "borrow", locale: "en", title: "Loan apps and buy-now-pay-later",
    summary: "Mobile and app loans are fast, small and short. The fee looks small and the yearly cost is high.",
    points: [
      "Late fees and automatic rollovers are where the cost explodes.",
      "Some apps read your contacts and messages. Check permissions and refuse apps that harass contacts.",
      "Buy-now-pay-later is credit. Several small plans at once can exceed your budget.",
      "Repaying on time builds a credit history. Late payments damage it for years.",
    ],
    example: "Three “pay in 4” purchases of 40,000 F each mean 30,000 F of instalments due every period, before any other expense.",
    watchOut: "Speed is the product. A loan granted in two minutes deserves ten minutes of arithmetic.",
    aliases: ["loan app", "nano credit", "mobile loan", "bnpl", "pay later", "instant loan", "overdraft", "airtime credit"], sources: [DIGITAL],
  },
  {
    id: "debt-capacity", area: "borrow", locale: "en", title: "Useful debt, costly debt, and how much",
    summary: "Useful debt finances something that earns or lasts. Costly debt finances consumption that is gone before the last instalment.",
    points: [
      "Rule of thumb: keep all instalments under about one third of your regular income.",
      "Test before signing: live one month as if you were already paying the instalment.",
      "Count the income the purchase brings, if any, and be honest about it.",
      "Never sign as guarantor unless you could repay the loan yourself.",
    ],
    example: "Income 120,000 F: total instalments should stay near or under 40,000 F. A motorbike that brings 3,000 F a day in deliveries is not the same debt as a television.",
    watchOut: "A guarantor is a borrower who received nothing.",
    aliases: ["good debt", "bad debt", "how much can i borrow", "guarantor", "debt ratio", "afford"], sources: [YOUTH],
  },
  {
    id: "out-of-debt", area: "borrow", locale: "en", title: "Getting out of debt",
    summary: "Getting out starts with a complete list and one rule: stop adding debt.",
    points: [
      "List every debt: lender, amount left, rate, instalment, due date.",
      "Never borrow to repay, unless the new loan is clearly cheaper and replaces the old one.",
      "Two methods: highest rate first (cheapest overall) or smallest balance first (fastest wins). Pay the minimum on the rest.",
      "Talk to lenders before missing a payment. Rescheduling is easier early.",
    ],
    example: "Two debts: 30,000 F at 10 % a month and 100,000 F at 2 % a month. Every extra franc goes to the 30,000 F first: it costs 3,000 F a month in interest against 2,000 F for the larger one.",
    watchOut: "Danger signs: borrowing for food, hiding debts, several lenders at once.",
    aliases: ["over-indebted", "repay", "debt snowball", "avalanche", "reschedule", "moneylender", "too many debts"], sources: [YOUTH],
  },
  // ── Protect and build ───────────────────────────────────────────────────
  {
    id: "insurance", area: "protect", locale: "en", title: "Insurance: a little to avoid losing a lot",
    summary: "Insurance transfers a risk you could not bear alone, in exchange for a premium.",
    points: [
      "Insure what would ruin you: health, the earner’s death or disability, a work tool, a harvest.",
      "Read three things: what is covered, what is excluded, how to claim.",
      "Micro-insurance and mutual health schemes exist for small budgets.",
      "Check that the insurer is licensed, and keep the contract and receipts.",
    ],
    example: "A hospital stay of 200,000 F can erase a year of savings. Health cover at 2,500 F a month costs 30,000 F a year.",
    watchOut: "Insurance is not a savings product. A year without a claim is a good year, not wasted money.",
    aliases: ["insurance", "health cover", "mutual", "micro-insurance", "premium", "claim", "accident"], sources: [YOUTH],
  },
  {
    id: "consumer-rights", area: "protect", locale: "en", title: "Your rights as a financial customer",
    summary: "A financial customer has rights: clear prices, a contract, a receipt, and a way to complain.",
    points: [
      "Ask for the price list and the contract before you sign, and keep a copy.",
      "Complain first to the provider, in writing, and keep the reference number.",
      "If it stays unresolved, go to the regulator or a consumer association.",
      "Your personal data is for the service only. You can refuse marketing use.",
    ],
    example: "A wrong transfer or a debit you do not recognise: note the date, amount and transaction ID, contact the official customer service the same day and ask for a complaint number.",
    watchOut: "Only licensed providers answer to a regulator. A licence is what gives your complaint weight.",
    aliases: ["complaint", "rights", "regulator", "contract", "receipt", "customer service", "dispute", "personal data"], sources: [YOUTH, BCEAO],
  },
  {
    id: "business-money", area: "protect", locale: "en", title: "Business money is not your money",
    summary: "A small business survives when its money is counted separately from its owner’s.",
    points: [
      "Separate wallets or accounts for the business and for yourself.",
      "Pay yourself a fixed amount. The rest stays to buy stock and grow.",
      "Price = costs + your time + margin. Revenue is not profit.",
      "Record every sale and expense daily. Cash in the till proves nothing.",
    ],
    example: "Sales of 300,000 F, stock 180,000 F, transport and fees 30,000 F, your pay 50,000 F: the profit is 40,000 F, not 300,000 F.",
    watchOut: "Selling on credit to friends is lending. Write it down and set a date.",
    aliases: ["business", "shop", "entrepreneur", "profit", "revenue", "pricing", "stock", "startup", "customers credit"], sources: [YOUTH],
  },
  {
    id: "net-worth-records", area: "protect", locale: "en", title: "Know what you own and what you owe",
    summary: "Net worth is what you own minus what you owe. It shows progress better than income does.",
    points: [
      "Own: savings, equipment, land, money owed to you. Owe: loans, credit, unpaid bills.",
      "Compute it once or twice a year and compare with last time.",
      "Keep documents safe and copied: ID, contracts, receipts, land papers, account numbers.",
      "Tell one trusted person where the documents are.",
    ],
    example: "Savings of 150,000 F plus a motorbike worth 400,000 F, minus 250,000 F left on a loan: a net worth of 300,000 F.",
    watchOut: "A high income with a negative net worth is fragile.",
    aliases: ["net worth", "assets", "liabilities", "documents", "records", "what i own", "what i owe"], sources: [YOUTH],
  },
  {
    id: "long-term", area: "protect", locale: "en", title: "The long term: studies, home, retirement",
    summary: "Long goals need small, regular, automatic amounts and a lot of time.",
    points: [
      "Training that raises your income is often the best first investment.",
      "Check whether you are registered with a pension or social security scheme and whether contributions are really paid.",
      "Land and housing: verify the title and the seller before paying.",
      "Review the plan once a year; raise the amount when income rises.",
    ],
    example: "10,000 F a month for 20 years is 2,400,000 F paid in. At 5 % a year compounded, it grows to about 4,100,000 F.",
    watchOut: "A cheap plot with a dispute attached is expensive.",
    aliases: ["retirement", "pension", "social security", "house", "land", "studies", "training", "long term", "future"], sources: [YOUTH],
  },
];
