import type { LiteracyUnit } from "./corpus.js";

const YOUTH = "oecd-infe-youth";
const DIGITAL = "eu-oecd-digital";
const BCEAO = "bceao";
const BRVM = "brvm";

export const LITERACY_UNITS_FR: LiteracyUnit[] = [
  // ── Gagner ──────────────────────────────────────────────────────────────
  {
    id: "money-goals", area: "earn", locale: "fr", title: "Donner un rôle à son argent",
    summary: "L’argent est un outil. Décider ce qu’il doit faire ce mois-ci, cette année et dans cinq ans est la première compétence financière.",
    points: [
      "Écrivez chaque objectif avec un montant et une date : « 150 000 F pour un ordinateur d’ici juin ».",
      "Classez les objectifs par horizon : court (semaines), moyen (mois), long (années).",
      "Un objectif avec un montant mensuel devient une habitude ; sans montant, il reste un souhait.",
      "Revoyez vos objectifs quand vos revenus ou votre vie changent.",
    ],
    example: "Un ordinateur à 150 000 F en 10 mois, c’est 15 000 F par mois. Si c’est trop, changez la date ou le modèle, pas l’habitude d’épargner.",
    watchOut: "Les objectifs copiés sur les réseaux sociaux appartiennent à la vie de quelqu’un d’autre. Partez de la vôtre.",
    aliases: ["objectif", "but", "projet", "rêve", "priorités", "plan"], sources: [YOUTH],
  },
  {
    id: "first-income", area: "earn", locale: "fr", title: "Votre premier revenu",
    summary: "Les premiers mois de revenu installent des habitudes qui durent des années. Décidez les parts avant que l’argent arrive.",
    points: [
      "Avant la paie, décidez trois parts : vivre, épargner, famille ou dons.",
      "Épargnez d’abord, le jour de la paie, même un petit montant.",
      "Gardez le même train de vie les trois premiers mois, puis augmentez-le doucement.",
      "Recevez vos revenus sur un compte à votre nom : l’historique aide ensuite à louer, emprunter ou prouver ses revenus.",
    ],
    example: "Première paie de 120 000 F : 12 000 F épargnés le premier jour (10 %), 20 000 F pour la famille, 88 000 F pour vivre. Les 10 % sont un point de départ, pas une loi.",
    watchOut: "Tout dépenser « parce que c’est la première » devient souvent la règle.",
    aliases: ["salaire", "premier emploi", "stage", "bourse", "paie", "argent de poche"], sources: [YOUTH],
  },
  {
    id: "irregular-income", area: "earn", locale: "fr", title: "Débrouille et revenus irréguliers",
    summary: "Freelance, commerce, petits boulots et activités à côté paient de façon inégale. La compétence, c’est d’en faire une vie stable.",
    points: [
      "Calculez votre mois moyen sur les six derniers mois, puis budgétez sur un mois faible, pas sur le meilleur.",
      "Les bons mois, remplissez une réserve ; les mois faibles, payez-vous avec.",
      "Gardez l’argent de l’activité et l’argent personnel dans deux portefeuilles ou comptes séparés.",
      "Mettez de côté ce dont l’activité a besoin (stock, connexion, frais, impôts) avant de compter le bénéfice.",
    ],
    example: "Six mois rapportent 40 000, 90 000, 60 000, 30 000, 110 000 et 70 000 F : 400 000 F au total, environ 66 700 F en moyenne, 30 000 F au pire. Prévoyez des dépenses de vie autour de 50 000 F et envoyez le surplus des bons mois dans la réserve.",
    watchOut: "Un très bon mois n’est pas un nouveau salaire.",
    aliases: ["freelance", "petit boulot", "gombo", "commerce", "commission", "saisonnier", "revenu variable", "activité à côté"], sources: [YOUTH],
  },
  {
    id: "family-support", area: "earn", locale: "fr", title: "Soutenir sa famille sans couler",
    summary: "Aider la famille est une valeur et une vraie ligne de budget. Prévue, elle dure ; improvisée, elle vous épuise et aide moins.",
    points: [
      "Prévoyez le soutien familial comme un loyer : un montant mensuel tenable, annoncé clairement.",
      "Constituez d’abord votre propre réserve d’urgence ; un soutien ruiné n’aide personne.",
      "Préférez l’aide qui construit : scolarité, outil de travail, couverture santé.",
      "Distinguez l’urgence de l’habitude, et décidez à l’avance ce qui compte comme urgence.",
    ],
    example: "Revenu de 150 000 F : 20 000 F fixes pour la famille chaque mois et une cagnotte « urgences familiales » de 5 000 F se tiennent mieux que répondre à chaque demande avec ce qui reste.",
    watchOut: "Emprunter pour donner crée deux problèmes : le vôtre et le leur.",
    aliases: ["famille", "parents", "frères", "sœurs", "demandes", "solidarité", "obligation", "aider la famille", "black tax"], sources: [YOUTH],
  },
  {
    id: "lifestyle-pressure", area: "earn", locale: "fr", title: "Besoins, envies et pression sociale",
    summary: "Les besoins vous font vivre et travailler, les envies rendent la vie agréable. Les deux sont légitimes, dans cet ordre.",
    points: [
      "Train de vie qui gonfle : chaque augmentation disparaît si les dépenses montent à la même vitesse.",
      "Attendez 24 heures avant un achat impulsif, 30 jours pour un gros achat. La plupart des envies passent.",
      "Mesurez un prix en heures ou en mois de travail, pas par rapport à ce que possèdent les amis.",
      "Gardez un petit budget plaisir : un plan sans plaisir ne tient jamais.",
    ],
    example: "Un téléphone à 300 000 F avec un revenu de 100 000 F, c’est trois mois de travail. « Est-ce que je travaillerais trois mois pour ça ? » est une question plus claire que « est-ce que je peux payer la mensualité ? ».",
    watchOut: "Acheter pour paraître réussi retarde le moment de l’être.",
    aliases: ["impulsif", "pression", "statut", "téléphone", "mode", "frimer", "train de vie"], sources: [YOUTH],
  },
  // ── Dépenser ────────────────────────────────────────────────────────────
  {
    id: "budget-basics", area: "spend", locale: "fr", title: "Un budget en quatre lignes",
    summary: "Un budget donne un rôle à chaque franc avant le début du mois : revenus moins épargne, charges fixes et dépenses variables égale zéro.",
    points: [
      "Charges fixes : loyer, transport, scolarité, abonnements. Variables : nourriture, sorties, vêtements, connexion.",
      "Écrivez le budget avant le début du mois et ajustez-le en cours de mois.",
      "Quand une ligne monte, une autre doit baisser. L’épargne est la dernière à toucher.",
      "Un budget est un plan, pas une punition : prévoyez de l’argent pour le plaisir.",
    ],
    example: "Revenu de 100 000 F : 10 000 F d’épargne, 45 000 F de charges fixes, 45 000 F de dépenses variables. Si le transport augmente de 5 000 F, prenez-les sur les dépenses variables, pas sur l’épargne.",
    watchOut: "Un budget qu’on ne regarde plus est une liste de souhaits.",
    aliases: ["budget", "prévoir", "plan mensuel", "dépenses", "comment faire un budget"], sources: [YOUTH],
  },
  {
    id: "budget-methods", area: "spend", locale: "fr", title: "50/30/20, enveloppes et cagnottes",
    summary: "Plusieurs méthodes simples existent. La meilleure est celle que vous utilisez encore après trois mois.",
    points: [
      "50/30/20 : environ la moitié pour les besoins, 30 % pour les envies, 20 % pour l’épargne et les dettes.",
      "Avec un petit revenu, les besoins peuvent prendre 70 %. Gardez l’ordre, changez les chiffres.",
      "Enveloppes ou cagnottes : une par catégorie ; quand elle est vide, la catégorie s’arrête.",
      "Budget base zéro : prévoir chaque franc chaque mois. Il convient aux revenus irréguliers.",
    ],
    example: "80 000 F répartis en 70/20/10 donnent 56 000 F pour les besoins, 16 000 F pour les envies et 8 000 F d’épargne.",
    watchOut: "Les pourcentages sont un guide. Un loyer qui prend la moitié du revenu est une question de logement, pas un échec de budget.",
    aliases: ["50 30 20", "enveloppe", "cagnotte", "base zéro", "règle", "méthode"], sources: [YOUTH],
  },
  {
    id: "tracking-spending", area: "spend", locale: "fr", title: "Où part vraiment l’argent",
    summary: "Noter chaque dépense pendant un mois révèle deux ou trois fuites que personne ne remarque autrement.",
    points: [
      "Les petites dépenses quotidiennes s’additionnent : 500 F par jour, c’est 15 000 F par mois et 182 500 F par an.",
      "Fuites habituelles : forfaits internet, grignotage, taxis, frais de retrait, paris.",
      "Suivez par catégorie et regardez une fois par semaine, pas une fois par an.",
      "Changez une chose à la fois ; trois changements d’un coup tiennent rarement.",
    ],
    example: "Trois retraits d’espèces par semaine à 300 F de frais coûtent environ 3 900 F par mois. Un seul retrait prévu par semaine réduit cela des deux tiers.",
    watchOut: "Suivre sert à voir clair, pas à culpabiliser.",
    aliases: ["suivre", "noter", "fuites", "petites dépenses", "forfait", "frais", "où va mon argent"], sources: [YOUTH],
  },
  {
    id: "inflation", area: "spend", locale: "fr", title: "L’inflation : pourquoi les prix montent",
    summary: "L’inflation est la hausse générale des prix. Le même argent achète moins avec le temps.",
    points: [
      "L’argent qui dort à 0 % perd du pouvoir d’achat chaque année.",
      "Ce qui compte, c’est le rendement réel : le taux d’intérêt moins l’inflation.",
      "Les revenus doivent suivre les prix : renégociez régulièrement salaire et tarifs.",
      "Pour une hausse connue sur un bien durable dont vous avez besoin, acheter plus tôt peut être rationnel. Stocker par peur ne l’est pas.",
    ],
    example: "Avec 3 % d’inflation, un panier à 100 000 F coûte environ 103 000 F l’an prochain. Une épargne à 2 % est passée à 102 000 F : le chiffre a monté, le pouvoir d’achat a baissé.",
    watchOut: "Un produit « garanti » qui rapporte moins que l’inflation garantit une perte lente.",
    aliases: ["prix", "vie chère", "coût de la vie", "pouvoir d’achat", "rendement réel"], sources: [YOUTH],
  },
  {
    id: "big-moments", area: "spend", locale: "fr", title: "Préparer les grands moments",
    summary: "Scolarité, avance de loyer, fêtes, mariages, funérailles et voyages sont prévisibles. Ce qui est prévisible peut s’épargner.",
    points: [
      "Placez chaque grosse dépense de l’année sur un calendrier, avec son montant.",
      "Divisez le montant par les mois restants et épargnez cette somme chaque mois.",
      "Gardez ces cagnottes séparées de la réserve d’urgence.",
      "Fixez votre plafond pour les événements sociaux avant de recevoir l’invitation.",
    ],
    example: "Scolarité de 90 000 F à payer en octobre : en épargnant dès janvier, il faut 10 000 F par mois pendant neuf mois. En commençant en juillet, 30 000 F par mois.",
    watchOut: "Une dépense qui revient chaque année n’est pas une urgence.",
    aliases: ["scolarité", "frais scolaires", "avance de loyer", "caution", "mariage", "funérailles", "fête", "tabaski", "noël", "voyage", "dépense prévue"], sources: [YOUTH],
  },
  // ── Argent numérique ────────────────────────────────────────────────────
  {
    id: "mobile-money", area: "digital", locale: "fr", title: "Le mobile money, bien utilisé",
    summary: "Un portefeuille mobile est un compte sur votre SIM, géré par un opérateur selon les règles de la banque centrale. L’argent est à vous, pas à l’agent.",
    points: [
      "Enregistrez le portefeuille à votre nom avec votre pièce d’identité : plafonds plus élevés et moyen de le récupérer.",
      "Connaissez la grille tarifaire. Les dépôts sont en général gratuits ; les retraits et les transferts vers d’autres réseaux sont en général payants. Vérifiez la grille actuelle de votre opérateur.",
      "Gardez chaque message de confirmation : c’est votre reçu.",
      "L’épargne gardée en mobile money doit être dans un portefeuille ou un compte séparé de l’argent du quotidien.",
    ],
    example: "Payer un commerçant depuis le portefeuille coûte souvent moins cher que retirer d’abord des espèces. Comparez les deux frais avant votre prochain achat.",
    watchOut: "Ne donnez jamais votre code PIN, même à un agent ou au « service client ». Aucun vrai agent n’en a besoin.",
    aliases: ["portefeuille", "orange money", "wave", "moov", "mtn momo", "agent", "retrait", "frais", "identification", "plafond"], sources: [DIGITAL, BCEAO],
  },
  {
    id: "accounts", area: "digital", locale: "fr", title: "Banque, microfinance ou compte numérique",
    summary: "Les comptes diffèrent par leur coût, leur accès et leur sécurité. En choisir un est une comparaison, pas une affaire de prestige.",
    points: [
      "Comparez quatre choses : frais mensuels, solde minimum, accès (agents, agences, application) et ce que le compte rapporte.",
      "Les banques et les institutions de microfinance agréées sont supervisées. Demandez si une institution est agréée avant de déposer.",
      "Un historique de compte à votre nom aide à louer, emprunter et prouver ses revenus.",
      "Utilisez le portefeuille pour le quotidien et un compte que vous n’avez pas dans la poche pour l’épargne.",
    ],
    example: "Un compte à 1 000 F de frais mensuels coûte 12 000 F par an. S’il ne rapporte rien et que vous n’allez jamais en agence, une option moins chère fait le même travail.",
    watchOut: "Une application qui prend des dépôts sans agrément n’est pas une banque, quelle que soit son apparence.",
    aliases: ["banque", "microfinance", "néobanque", "compte épargne", "ouvrir un compte", "frais", "agréé", "sfd"], sources: [DIGITAL, BCEAO],
  },
  {
    id: "digital-safety", area: "digital", locale: "fr", title: "Protéger l’argent de son téléphone",
    summary: "La plupart des vols numériques ne cassent pas la technologie. Ils convainquent le propriétaire de donner la clé.",
    points: [
      "Un code PIN secret, différent de votre date de naissance, jamais partagé, jamais saisi sur un lien reçu.",
      "Échange de SIM : si votre ligne se coupe sans raison, appelez l’opérateur tout de suite et bloquez le portefeuille.",
      "Les messages annonçant un gain, un compte bloqué ou un « transfert par erreur » poussent à agir vite. Ralentissez et vérifiez par le numéro officiel.",
      "Verrouillez votre téléphone, mettez à jour vos applications et n’installez que depuis la boutique officielle.",
    ],
    example: "« Je vous ai envoyé 25 000 F par erreur, renvoyez-les s’il vous plaît. » Vérifiez d’abord votre vrai solde. Si rien n’est arrivé, c’est une arnaque. Si l’argent est bien arrivé, demandez à l’opérateur d’annuler plutôt que de renvoyer vous-même.",
    watchOut: "L’urgence est l’outil principal de l’escroc. Un vrai problème survit à dix minutes de vérification.",
    aliases: ["pin", "code secret", "sim swap", "hameçonnage", "piratage", "faux agent", "otp", "sécurité", "téléphone volé", "fraude"], sources: [DIGITAL],
  },
  {
    id: "scams-ponzi", area: "digital", locale: "fr", title: "Arnaques et systèmes pyramidaux",
    summary: "Un système pyramidal paie les premiers membres avec l’argent des nouveaux. Il s’effondre quand le recrutement ralentit, à chaque fois.",
    points: [
      "Signaux d’alerte : rendement élevé garanti, pression pour recruter, urgence, pas de produit clair, pas d’agrément.",
      "Les captures d’écran de gains et les témoignages dans les groupes WhatsApp ou Telegram ne prouvent rien.",
      "Posez deux questions : qui est agréé pour recevoir cet argent, et d’où vient le bénéfice ?",
      "L’ami ou le parent qui vous invite est le plus souvent une victime aussi, pas une garantie.",
    ],
    example: "« Déposez 50 000 F, recevez 100 000 F en 30 jours », c’est 100 % par mois. Aucune vraie activité ne tient ce rythme. C’est le dépôt de quelqu’un d’autre qui paie, jusqu’à ce que ce soit le vôtre.",
    watchOut: "Être payé une fois fait partie du piège : c’est ce qui vous fait apporter plus d’argent et plus de monde.",
    aliases: ["ponzi", "pyramide", "mlm", "marketing de réseau", "doubler son argent", "groupe d’investissement", "telegram", "groupe whatsapp", "arnaque", "escroquerie"], sources: [DIGITAL, YOUTH],
  },
  {
    id: "betting", area: "digital", locale: "fr", title: "Parier n’est pas un revenu",
    summary: "Les opérateurs de paris intègrent une marge dans chaque cote. En moyenne les joueurs perdent, et plus ils jouent, plus la perte est sûre.",
    points: [
      "On se souvient d’un gain et on oublie dix pertes. Notez les paris comme n’importe quelle dépense pour voir la vérité.",
      "Parier pour se refaire ou pour payer une dette est le signal de danger.",
      "Si vous pariez pour le plaisir, fixez un montant mensuel de loisir et n’empruntez jamais pour cela.",
      "Les « pronostics sûrs » et les groupes payants gagnent sur leurs abonnés, pas sur leurs paris.",
    ],
    example: "1 000 F de paris par jour, c’est 30 000 F par mois. À cause de la marge de l’opérateur, le résultat attendu sur un an est une perte, pas un salaire. Les mêmes 30 000 F épargnés chaque mois font 360 000 F en un an.",
    watchOut: "Si vous n’arrivez pas à arrêter, parlez-en à une personne de confiance. C’est une dépendance connue, pas une faiblesse de caractère.",
    aliases: ["pari", "paris sportifs", "jeu", "cote", "casino", "loterie", "pronostic", "parifoot"], sources: [YOUTH],
  },
  {
    id: "remittances-fx", area: "digital", locale: "fr", title: "Envoyer de l’argent et taux de change",
    summary: "Un transfert coûte deux choses : les frais visibles et la marge sur le taux de change. Comparez ce qui arrive, pas les frais.",
    points: [
      "Le franc CFA (XOF) a une parité fixe avec l’euro : 1 euro = 655,957 F CFA. Les autres devises bougent chaque jour.",
      "Les services numériques sont souvent moins chers que les guichets en espèces. Comparez pour votre trajet.",
      "Pour un soutien régulier, des transferts moins nombreux et plus gros coûtent en général moins cher que beaucoup de petits.",
      "N’utilisez que des services agréés et gardez la référence de chaque transfert.",
    ],
    example: "Deux services envoient 100 euros. A prend 2 euros de frais avec un taux de 650 F par euro : 65 000 F arrivent pour 102 euros payés, soit environ 637 F par euro. B ne prend pas de frais avec un taux de 640 F : 64 000 F arrivent pour 100 euros payés, soit 640 F par euro. B est moins cher.",
    watchOut: "« Zéro frais » cache souvent un taux de change moins bon.",
    aliases: ["transfert", "diaspora", "envoyer de l’argent", "recevoir de l’argent", "taux de change", "euro", "dollar", "devise", "western union"], sources: [DIGITAL, BCEAO],
  },
  // ── Épargner et faire grandir ───────────────────────────────────────────
  {
    id: "emergency-fund", area: "grow", locale: "fr", title: "Se payer d’abord, se faire un coussin",
    summary: "L’épargne part le jour où le revenu arrive, pas avec ce qui reste. Le premier but est un coussin pour les urgences.",
    points: [
      "Automatisez si possible : un virement permanent le jour de la paie.",
      "Première cible : un mois de dépenses essentielles. Ensuite trois à six.",
      "Gardez-le accessible mais pas dans la poche : un portefeuille ou un compte séparé.",
      "Utilisez-le pour les vraies urgences seulement (santé, perte de revenu, réparation urgente), puis reconstituez-le.",
    ],
    example: "Dépenses essentielles de 60 000 F par mois : épargner 10 000 F par mois constitue le premier mois de coussin en six mois et trois mois (180 000 F) en dix-huit.",
    watchOut: "Une promotion n’est pas une urgence.",
    aliases: ["épargne", "urgence", "coussin", "réserve", "épargner", "se payer d’abord", "imprévu"], sources: [YOUTH],
  },
  {
    id: "where-to-save", area: "grow", locale: "fr", title: "Où garder son épargne",
    summary: "Jugez chaque endroit sur quatre critères : sécurité, accès, coût et ce qu’il rapporte.",
    points: [
      "Les espèces à la maison sont gratuites et immédiates, mais exposées au vol, au feu et à la tentation.",
      "Les portefeuilles et les comptes d’épargne en banque ou en microfinance sont plus sûrs et traçables. Certains rapportent des intérêts ou permettent de bloquer l’argent.",
      "Les groupes d’épargne (tontines, associations villageoises d’épargne) apportent discipline et solidarité. Leur sécurité dépend de membres connus et de règles écrites.",
      "Accordez l’endroit au but : accès immédiat pour les urgences, bloqué pour les objectifs.",
    ],
    example: "L’argent du quotidien dans le portefeuille, la réserve d’urgence sur un compte d’épargne séparé, l’objectif de l’an prochain dans un produit bloqué ou dans un groupe dont la date de versement correspond à l’objectif.",
    watchOut: "L’endroit le plus sûr est celui où vous ne pouvez pas prendre l’argent par réflexe.",
    aliases: ["tontine", "groupe d’épargne", "avec", "espèces à la maison", "compte épargne", "bloquer", "dépôt à terme", "où épargner"], sources: [YOUTH],
  },
  {
    id: "compound-interest", area: "grow", locale: "fr", title: "Intérêts composés : le temps est le moteur",
    summary: "L’intérêt simple est payé sur le capital seul. L’intérêt composé est payé sur le capital et sur les intérêts passés : la croissance s’accélère.",
    points: [
      "Plus vous commencez tôt, plus le temps travaille pour vous.",
      "Règle de 72 : années pour doubler ≈ 72 ÷ taux annuel.",
      "De petits montants réguliers battent un gros montant commencé tard.",
      "Les intérêts composés jouent aussi contre vous sur une dette.",
    ],
    example: "100 000 F à 6 % par an : après 5 ans, 130 000 F en intérêt simple et environ 133 800 F en composé. Après 20 ans, 220 000 F en simple et environ 320 700 F en composé. À 6 %, l’argent double en 12 ans environ.",
    watchOut: "Les intérêts composés demandent un taux réaliste. Une promesse de 10 % par mois n’en est pas : c’est une arnaque.",
    aliases: ["intérêt", "composé", "intérêt simple", "règle de 72", "croissance", "doubler", "taux"], sources: [YOUTH],
  },
  {
    id: "risk-return", area: "grow", locale: "fr", title: "Risque, rendement et diversification",
    summary: "Un rendement possible plus élevé vient toujours avec un risque plus élevé. « Élevé et garanti » n’existe pas.",
    points: [
      "Trois questions avant d’investir : puis-je perdre du capital, quand puis-je récupérer mon argent, combien cela coûte-t-il ?",
      "Diversifiez : plusieurs actifs, pas tous les œufs dans le même panier.",
      "Accordez le placement à l’horizon : l’argent nécessaire dans les deux ans ne doit pas être en risque.",
      "Comprenez-le ou laissez-le. La complexité n’est pas un signe de qualité.",
    ],
    example: "300 000 F prêtés entièrement à l’activité d’un ami, c’est un seul risque. La même somme répartie entre un compte d’épargne, un dépôt à terme et une petite part dans cette activité survit à un échec.",
    watchOut: "Les performances passées sont une histoire, pas une promesse.",
    aliases: ["risque", "rendement", "diversifier", "liquidité", "horizon", "placement sûr", "garanti"], sources: [YOUTH],
  },
  {
    id: "investing-basics", area: "grow", locale: "fr", title: "Investir : les grandes familles",
    summary: "Investir, c’est acheter quelque chose qui doit rapporter ou prendre de la valeur sur des années. Chaque famille a son risque et sa sortie.",
    points: [
      "Dépôts à terme : risque faible, rendement modeste, durée fixe.",
      "Obligations et bons du Trésor : vous prêtez à un État ou à une entreprise contre des intérêts.",
      "Actions : vous possédez une part d’entreprise et sa valeur bouge. Dans l’UEMOA, elles se négocient à la bourse régionale, la BRVM, par des intermédiaires agréés.",
      "Les fonds réunissent de nombreux investisseurs sur de nombreux actifs. Le terrain et votre propre activité sont aussi des investissements, peu liquides et avec leurs risques.",
    ],
    example: "Avant tout investissement, écrivez trois lignes : ce que j’achète, comment cela gagne de l’argent, comment j’en sors. Si une ligne reste vide, vous n’êtes pas encore prêt pour celui-là.",
    watchOut: "Ceci est de l’éducation. WiseMoney ne recommande aucun produit. Vérifiez que tout intermédiaire est agréé.",
    aliases: ["investir", "actions", "obligations", "bons du trésor", "brvm", "fonds", "terrain", "bourse", "sgi", "placement"], sources: [YOUTH, BRVM],
  },
  {
    id: "crypto-forex", area: "grow", locale: "fr", title: "Crypto et trading : retour au réel",
    summary: "Les cryptoactifs et le trading à court terme sont de la spéculation, pas de l’épargne. Les prix peuvent être divisés par deux en quelques semaines et la plupart des particuliers perdent.",
    points: [
      "Les cryptoactifs sont très volatils et n’ont pas cours légal dans la plupart des pays.",
      "Le trading de devises, de crypto ou sur « signaux » rapporte plus sûrement à la plateforme et au formateur qu’au trader.",
      "Les « académies » et gestionnaires de compte qui promettent un rendement mensuel sont un format d’arnaque courant.",
      "Si vous voulez quand même en avoir : seulement de l’argent que vous pouvez perdre entièrement, après la réserve d’urgence, jamais emprunté.",
    ],
    example: "« Envoyez 100 000 F, notre trader rapporte 30 % par mois » revient à multiplier l’argent par 23 environ en un an. Aucun fonds au monde ne fait cela. La promesse elle-même est la preuve de la fraude.",
    watchOut: "Une crypto perdue ou volée se récupère rarement, et il n’y a en général personne auprès de qui se plaindre.",
    aliases: ["bitcoin", "crypto", "forex", "trading", "signaux", "binance", "usdt", "trader", "académie", "nft"], sources: [DIGITAL],
  },
  // ── Emprunter ───────────────────────────────────────────────────────────
  {
    id: "credit-basics", area: "borrow", locale: "fr", title: "Comment fonctionne un crédit",
    summary: "Trois chiffres définissent un prêt : le capital emprunté, le taux d’intérêt et la durée. Les frais et l’assurance s’ajoutent.",
    points: [
      "Chaque échéance rembourse une part de capital et une part d’intérêts.",
      "Une durée plus longue donne des échéances plus petites et plus d’intérêts au total.",
      "Empruntez pour quelque chose qui dure plus longtemps que le prêt.",
      "Demandez le tableau de remboursement avant de signer, et gardez-le.",
    ],
    example: "200 000 F sur 12 mois à 1,5 % par mois sur le capital initial : 3 000 F d’intérêts par mois, 36 000 F au total. Vous remboursez 236 000 F, soit environ 19 700 F par mois.",
    watchOut: "L’échéance dit si vous pouvez payer. Le total dit ce que cela coûte.",
    aliases: ["prêt", "crédit", "emprunter", "échéance", "mensualité", "taux d’intérêt", "remboursement", "tableau d’amortissement"], sources: [YOUTH],
  },
  {
    id: "true-cost-credit", area: "borrow", locale: "fr", title: "Le vrai coût d’un prêt",
    summary: "Le vrai prix d’un prêt, c’est tout ce que vous payez en plus du capital, exprimé par an.",
    points: [
      "Additionnez tout : intérêts, frais de dossier, assurance, épargne obligatoire.",
      "Le taux effectif global (TEG) réunit tout en un seul pourcentage annuel. C’est le chiffre à comparer.",
      "Un « petit » taux par semaine ou par mois est un gros taux par an.",
      "Dans l’UEMOA, la loi fixe un taux maximum, le taux d’usure. Les prêteurs agréés doivent le respecter et annoncer leur taux.",
    ],
    example: "Emprunter 20 000 F et rembourser 22 000 F après 30 jours : 10 % pour un mois. Répété toute l’année, cela fait 120 % par an, avant même de composer les intérêts.",
    watchOut: "Un prêteur qui refuse d’annoncer le taux annuel vous dit déjà quelque chose.",
    aliases: ["teg", "taeg", "coût du crédit", "frais de dossier", "usure", "intérêt par mois", "prêt cher"], sources: [YOUTH, BCEAO],
  },
  {
    id: "digital-loans", area: "borrow", locale: "fr", title: "Applis de prêt et paiement fractionné",
    summary: "Les prêts par mobile et par application sont rapides, petits et courts. Les frais paraissent faibles et le coût annuel est élevé.",
    points: [
      "Les pénalités de retard et les renouvellements automatiques font exploser le coût.",
      "Certaines applications lisent vos contacts et vos messages. Vérifiez les autorisations et refusez celles qui harcèlent les contacts.",
      "Le paiement fractionné est un crédit. Plusieurs petits plans en même temps peuvent dépasser votre budget.",
      "Rembourser à temps construit un historique de crédit. Les retards l’abîment pour des années.",
    ],
    example: "Trois achats « en 4 fois » de 40 000 F chacun, ce sont 30 000 F d’échéances à payer à chaque période, avant toute autre dépense.",
    watchOut: "La vitesse est le produit. Un prêt accordé en deux minutes mérite dix minutes de calcul.",
    aliases: ["appli de prêt", "nano crédit", "prêt mobile", "paiement en plusieurs fois", "payer plus tard", "prêt instantané", "découvert", "crédit de communication"], sources: [DIGITAL],
  },
  {
    id: "debt-capacity", area: "borrow", locale: "fr", title: "Dette utile, dette coûteuse, et combien",
    summary: "Une dette utile finance ce qui rapporte ou qui dure. Une dette coûteuse finance une consommation disparue avant la dernière échéance.",
    points: [
      "Repère : gardez l’ensemble des échéances sous un tiers environ de votre revenu régulier.",
      "Testez avant de signer : vivez un mois comme si vous payiez déjà l’échéance.",
      "Comptez le revenu que l’achat rapporte, s’il y en a, et soyez honnête.",
      "Ne vous portez jamais caution sans pouvoir rembourser le prêt vous-même.",
    ],
    example: "Revenu de 120 000 F : le total des échéances doit rester autour ou en dessous de 40 000 F. Une moto qui rapporte 3 000 F par jour en livraisons n’est pas la même dette qu’une télévision.",
    watchOut: "Une caution est un emprunteur qui n’a rien reçu.",
    aliases: ["bonne dette", "mauvaise dette", "combien emprunter", "caution", "taux d’endettement", "capacité"], sources: [YOUTH],
  },
  {
    id: "out-of-debt", area: "borrow", locale: "fr", title: "Sortir des dettes",
    summary: "En sortir commence par une liste complète et une règle : ne plus ajouter de dette.",
    points: [
      "Listez chaque dette : prêteur, montant restant, taux, échéance, date.",
      "N’empruntez jamais pour rembourser, sauf si le nouveau prêt est nettement moins cher et remplace l’ancien.",
      "Deux méthodes : le taux le plus élevé d’abord (le moins cher au total) ou le plus petit solde d’abord (victoires rapides). Payez le minimum sur le reste.",
      "Parlez aux prêteurs avant de manquer une échéance. Un rééchelonnement est plus facile tôt.",
    ],
    example: "Deux dettes : 30 000 F à 10 % par mois et 100 000 F à 2 % par mois. Chaque franc en plus va d’abord sur les 30 000 F : ils coûtent 3 000 F d’intérêts par mois contre 2 000 F pour la plus grosse.",
    watchOut: "Signaux de danger : emprunter pour manger, cacher ses dettes, plusieurs prêteurs à la fois.",
    aliases: ["surendettement", "rembourser", "boule de neige", "avalanche", "rééchelonner", "usurier", "trop de dettes"], sources: [YOUTH],
  },
  // ── Protéger et construire ──────────────────────────────────────────────
  {
    id: "insurance", area: "protect", locale: "fr", title: "L’assurance : un peu pour ne pas perdre beaucoup",
    summary: "L’assurance transfère un risque que vous ne pourriez pas porter seul, en échange d’une prime.",
    points: [
      "Assurez ce qui vous ruinerait : la santé, le décès ou l’invalidité de celui qui gagne, un outil de travail, une récolte.",
      "Lisez trois choses : ce qui est couvert, ce qui est exclu, comment déclarer.",
      "La micro-assurance et les mutuelles de santé existent pour les petits budgets.",
      "Vérifiez que l’assureur est agréé, et gardez le contrat et les reçus.",
    ],
    example: "Une hospitalisation à 200 000 F peut effacer un an d’épargne. Une couverture santé à 2 500 F par mois coûte 30 000 F par an.",
    watchOut: "L’assurance n’est pas un produit d’épargne. Une année sans sinistre est une bonne année, pas de l’argent perdu.",
    aliases: ["assurance", "couverture santé", "mutuelle", "micro-assurance", "prime", "sinistre", "accident"], sources: [YOUTH],
  },
  {
    id: "consumer-rights", area: "protect", locale: "fr", title: "Vos droits de client financier",
    summary: "Un client financier a des droits : des prix clairs, un contrat, un reçu et un moyen de réclamer.",
    points: [
      "Demandez la grille tarifaire et le contrat avant de signer, et gardez une copie.",
      "Réclamez d’abord auprès du prestataire, par écrit, et gardez le numéro de référence.",
      "Sans solution, adressez-vous au régulateur ou à une association de consommateurs.",
      "Vos données personnelles servent au service seulement. Vous pouvez refuser l’usage publicitaire.",
    ],
    example: "Un transfert erroné ou un débit que vous ne reconnaissez pas : notez la date, le montant et l’identifiant de la transaction, contactez le service client officiel le jour même et demandez un numéro de réclamation.",
    watchOut: "Seuls les prestataires agréés répondent à un régulateur. C’est l’agrément qui donne du poids à votre réclamation.",
    aliases: ["réclamation", "droits", "régulateur", "contrat", "reçu", "service client", "litige", "données personnelles"], sources: [YOUTH, BCEAO],
  },
  {
    id: "business-money", area: "protect", locale: "fr", title: "L’argent de l’activité n’est pas le vôtre",
    summary: "Une petite activité survit quand son argent est compté séparément de celui de son propriétaire.",
    points: [
      "Des portefeuilles ou comptes séparés pour l’activité et pour vous.",
      "Payez-vous un montant fixe. Le reste sert à acheter du stock et à grandir.",
      "Prix = coûts + votre temps + marge. Le chiffre d’affaires n’est pas le bénéfice.",
      "Notez chaque vente et chaque dépense le jour même. L’argent dans la caisse ne prouve rien.",
    ],
    example: "Ventes de 300 000 F, stock 180 000 F, transport et frais 30 000 F, votre paie 50 000 F : le bénéfice est de 40 000 F, pas de 300 000 F.",
    watchOut: "Vendre à crédit aux amis, c’est prêter. Écrivez-le et fixez une date.",
    aliases: ["activité", "boutique", "entrepreneur", "bénéfice", "chiffre d’affaires", "prix", "stock", "startup", "crédit client", "commerce"], sources: [YOUTH],
  },
  {
    id: "net-worth-records", area: "protect", locale: "fr", title: "Savoir ce que l’on possède et ce que l’on doit",
    summary: "Le patrimoine net, c’est ce que vous possédez moins ce que vous devez. Il montre le progrès mieux que le revenu.",
    points: [
      "Vous possédez : épargne, équipement, terrain, argent qu’on vous doit. Vous devez : prêts, crédits, factures impayées.",
      "Calculez-le une ou deux fois par an et comparez avec la fois précédente.",
      "Gardez les documents en sécurité et en copie : pièce d’identité, contrats, reçus, papiers de terrain, numéros de compte.",
      "Dites à une personne de confiance où se trouvent les documents.",
    ],
    example: "Une épargne de 150 000 F et une moto qui vaut 400 000 F, moins 250 000 F restant sur un prêt : un patrimoine net de 300 000 F.",
    watchOut: "Un gros revenu avec un patrimoine net négatif est fragile.",
    aliases: ["patrimoine", "actifs", "passifs", "documents", "papiers", "ce que je possède", "ce que je dois"], sources: [YOUTH],
  },
  {
    id: "long-term", area: "protect", locale: "fr", title: "Le long terme : études, logement, retraite",
    summary: "Les objectifs longs demandent de petits montants réguliers, automatiques, et beaucoup de temps.",
    points: [
      "Une formation qui augmente vos revenus est souvent le meilleur premier investissement.",
      "Vérifiez si vous êtes inscrit à une caisse de retraite ou de sécurité sociale et si les cotisations sont vraiment versées.",
      "Terrain et logement : vérifiez le titre et le vendeur avant de payer.",
      "Revoyez le plan une fois par an ; augmentez le montant quand le revenu augmente.",
    ],
    example: "10 000 F par mois pendant 20 ans, c’est 2 400 000 F versés. À 5 % par an composés, cela devient environ 4 100 000 F.",
    watchOut: "Un terrain pas cher avec un litige coûte cher.",
    aliases: ["retraite", "pension", "sécurité sociale", "cnss", "maison", "terrain", "études", "formation", "long terme", "avenir"], sources: [YOUTH],
  },
];
