// Generated by tools/literacy/assemble.py from apps/web/content/literacy/area-*.json. Do not edit by hand:
// change the lesson at its source and regenerate, so the evidence table stays true.
export const LITERACY_PATH = {
  "start": [
    "what-financial-literacy-is",
    "set-goals",
    "cost-your-goals",
    "savings-plan",
    "talk-about-money-at-home",
    "answer-requests-for-money"
  ],
  "manage": [
    "money-in-money-out",
    "essential-and-non-essential",
    "build-a-budget",
    "track-your-spending",
    "keep-your-papers",
    "stick-to-your-budget",
    "irregular-income",
    "responsible-money-habits",
    "spending-pressure",
    "business-money-apart",
    "business-records"
  ],
  "save": [
    "why-save",
    "emergency-fund",
    "pay-yourself-first",
    "give-savings-a-name",
    "reminders-and-small-amounts",
    "ways-to-save",
    "savings-groups",
    "savings-accounts-in-burkina",
    "interest-and-time",
    "rising-prices"
  ],
  "bank": [
    "what-a-bank-does",
    "what-microfinance-is",
    "formal-and-informal-finance",
    "open-an-account",
    "free-banking-services",
    "is-my-money-protected",
    "mobile-money-basics",
    "send-and-receive-money",
    "choose-your-institution",
    "your-rights-as-a-client"
  ],
  "borrow": [
    "ways-to-fund-a-project",
    "words-of-credit",
    "what-a-loan-really-costs",
    "the-legal-ceiling",
    "how-much-can-you-repay",
    "choose-a-lender",
    "when-debt-becomes-too-much",
    "your-credit-record",
    "borrow-for-what"
  ],
  "protect": [
    "risks-around-you",
    "ways-to-face-a-risk",
    "how-insurance-works",
    "read-and-use-a-policy",
    "health-and-social-cover-in-burkina",
    "spot-a-scam",
    "phone-and-mobile-money-fraud",
    "check-before-you-trust",
    "complain-and-get-help"
  ],
  "invest": [
    "saving-or-investing",
    "risk-and-return",
    "shares",
    "bonds-and-treasury-securities",
    "funds",
    "spread-your-risk",
    "the-brvm",
    "start-from-burkina",
    "what-investing-costs",
    "tax-on-investment-income",
    "questions-before-investing"
  ],
  "grow": [
    "what-a-portfolio-is",
    "choose-your-mix",
    "know-your-risk-profile",
    "keep-your-mix-in-balance",
    "manage-it-yourself-or-delegate",
    "invest-regularly",
    "measure-your-return",
    "know-what-you-own-and-owe",
    "taxes-in-plain-words",
    "retirement-in-burkina",
    "make-your-activity-official"
  ]
} as const;
