// Generated by tools/literacy/assemble.py from apps/web/content/literacy/area-*.json. Do not edit by hand:
// change the lesson at its source and regenerate, so the evidence table stays true.
export type LiteracySource = { name: string; url?: string };

export const LITERACY_SOURCES: Record<string, LiteracySource> = {
  "oecd-2020": {
    "name": "OECD — Recommendation of the Council on Financial Literacy, OECD/LEGAL/0461 (2020)",
    "url": "https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0461"
  },
  "oecd-infe-2023": {
    "name": "OECD — OECD/INFE 2023 International Survey of Adult Financial Literacy (2023)",
    "url": "https://www.oecd.org/content/dam/oecd/en/publications/reports/2023/12/oecd-infe-2023-international-survey-of-adult-financial-literacy_8ce94e2c/56003a32-en.pdf"
  },
  "cfpb-wellbeing-2015": {
    "name": "US CFPB — Financial well-being: The goal of financial education (2015)",
    "url": "https://files.consumerfinance.gov/f/201501_cfpb_report_financial-well-being.pdf"
  },
  "afi-nfes-2021": {
    "name": "Alliance for Financial Inclusion — National Financial Education Strategies Toolkit (2021)",
    "url": "https://www.afi-global.org/wp-content/uploads/2024/10/NFES_toolkit_22082022.pdf"
  },
  "st-pif-2023": {
    "name": "ST-PIF (Burkina Faso) — Éducation financière, cahier du participant (2023 ; copie non officielle)",
    "url": "https://fr.scribd.com/document/744857863/inclusion-financiere"
  },
  "dgjep-2018": {
    "name": "Ministère de la Jeunesse (DGJEP, Burkina Faso) — Formation des jeunes promoteurs en éducation financière, cahier du participant (2018 ; copie non officielle)",
    "url": "https://fr.scribd.com/document/898056788/Cahier-Participant"
  },
  "finscope-bf-2016": {
    "name": "FinMark Trust — FinScope Burkina Faso 2016, Youth Dashboard",
    "url": "https://www.finmark.org.za/system/documents/files/000/000/235/original/Burkina-Faso_Dashboard_Youth_English.pdf"
  },
  "ilo-ci-2023": {
    "name": "OIT — Éducation financière pour les cultivateurs et les travailleurs ruraux en Côte d'Ivoire, Livret de l'apprenant (2023)",
    "url": "https://www.ilo.org/sites/default/files/wcmsp5/groups/public/%40ed_emp/%40emp_ent/documents/instructionalmaterial/wcms_900276.pdf"
  },
  "cfpb-ymyg": {
    "name": "CFPB — Your Money, Your Goals: A financial empowerment toolkit (2020)",
    "url": "https://files.consumerfinance.gov/f/documents/cfpb_your-money-your-goals_financial-empowerment_toolkit.pdf"
  },
  "aflatoun": {
    "name": "Aflatoun International — AflaYouth, manuel (extraits, 2024)",
    "url": "https://aflatoun.org/wp-content/uploads/2026/01/AflaYouth_FR_AllBooks_Sample.pdf"
  },
  "lefaso": {
    "name": "LeFaso.net — articles et commentaires de lecteurs (2012–2026)",
    "url": "https://lefaso.net"
  },
  "boltz-senegal-2019": {
    "name": "Boltz, Marazyan & Villar — Income hiding and informal redistribution: A lab-in-the-field experiment in Senegal, Journal of Development Economics 137 (2019)",
    "url": "https://shs.hal.science/halshs-02377013"
  },
  "ilo-iyb": {
    "name": "ILO — Improve Your Business (IYB): Record Keeping; Planning for Your Business; French edition GERME: la tenue des registres (2015)",
    "url": "https://researchrepository.ilo.org/esploro/outputs/encyclopediaEntry/Improve-your-business/995219387802676"
  },
  "cfpb-building-blocks": {
    "name": "CFPB — Learn about the building blocks of financial capability (page last modified 12 December 2024)",
    "url": "https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/learn/"
  },
  "fdic-money-smart": {
    "name": "FDIC — Money Smart for Young Adults, participant guides (2022)",
    "url": "https://www.fdic.gov/consumer-resource-center/money-smart-young-adults"
  },
  "fdic-money-smart-adults": {
    "name": "FDIC — Money Smart for Adults, Module 1: Your Money Values and Influences, Participant Guide (2018)",
    "url": "https://www.fdic.gov/consumer-resource-center/money-smart-adults"
  },
  "fcac-budget": {
    "name": "Financial Consumer Agency of Canada — Making a budget (read 2026-10-03)",
    "url": "https://www.canada.ca/en/financial-consumer-agency/services/make-budget.html"
  },
  "fcac-strategy": {
    "name": "Financial Consumer Agency of Canada — Make Change that Counts: National Financial Literacy Strategy 2021-2026 (2021)",
    "url": "https://www.canada.ca/en/financial-consumer-agency/programs/financial-literacy/financial-literacy-strategy-2021-2026.html"
  },
  "asic-moneysmart": {
    "name": "ASIC Moneysmart (Australia) — budgeting and investing guides",
    "url": "https://moneysmart.gov.au/how-to-invest/develop-an-investing-plan"
  },
  "banque-de-france": {
    "name": "Banque de France — ABC de l'économie et Mes questions d'argent",
    "url": "https://www.mesquestionsdargent.fr"
  },
  "banque-de-france-mqda": {
    "name": "Banque de France — Mes questions d'argent: « Pourquoi épargner ? »; « Économisez 1001€ en 1 an, le défi EDUCFI » (undated pages, read 2026)",
    "url": "https://www.mesquestionsdargent.fr/epargne-et-placements/pourquoi-epargner"
  },
  "findex-2025": {
    "name": "World Bank — Global Findex 2025, Little Data Book on Financial Inclusion (survey year 2024)",
    "url": "https://thedocs.worldbank.org/en/doc/be6615202d1f08a25855c8ac2d615122-0050012025/related/Little-Data-Book-2025-Web.pdf"
  },
  "cfpb-emergency-fund": {
    "name": "CFPB — An essential guide to building an emergency fund (page last modified 29 October 2025)",
    "url": "https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/"
  },
  "sec-roadmap": {
    "name": "US SEC — Saving and Investing: A Roadmap To Your Financial Security (2011)",
    "url": "https://www.sec.gov/investor/pubs/sec-guide-to-savings-and-investing.pdf"
  },
  "moneyhelper-uk": {
    "name": "UK MoneyHelper (MaPS) — Managing your money, beginner's guide (archived copy of 19 August 2026)",
    "url": "https://web.archive.org/web/20260819164856/https://www.moneyhelper.org.uk/en/everyday-money/budgeting/beginners-guide-to-managing-your-money"
  },
  "jpal-ipa": {
    "name": "J-PAL et IPA — évaluations sur l'épargne (bulletin 2021 et fiches d'évaluation)",
    "url": "https://www.povertyactionlab.org/sites/default/files/publication/Commitment-Savings-Bulletin-5.21.21.pdf"
  },
  "care-vsla": {
    "name": "CARE — Village Savings and Loan Associations Training Manual (revised December 2025)",
    "url": "https://www.care.org/wp-content/uploads/2026/01/CARE-VSLA-Manual.pdf"
  },
  "burkina24-tontine": {
    "name": "Burkina24 (press) — Tontine en ligne : Risquer le paquet pour du CFA craquant ! (28 April 2024)",
    "url": "https://burkina24.com/2024/04/28/tontine-en-ligne-risquer-le-paquet-pour-du-cfa-craquant/"
  },
  "umoa-savings-2014": {
    "name": "UMOA Council of Ministers — Décision n° CM/UMOA/016/09/2014 on the remuneration of regulated savings products (signed 24 September 2014, in force 1 January 2015)",
    "url": "https://www.cb-umoa.org/sites/default/files/2025-01/Decision%20portant%20conditions%20de%20remuneration%20des%20produits%20d%20epargne%20reglementes.pdf"
  },
  "fgdr-umoa": {
    "name": "BCEAO — Présentation du Fonds de Garantie des Dépôts et de Résolution dans l'UMOA (Dakar, 28 October 2019)",
    "url": "https://www.bceao.int/sites/default/files/inline-files/Pr%C3%A9sentation%20du%20Fonds%20de%20Garantie%20des%20D%C3%A9p%C3%B4ts%20et%20R%C3%A9solution%20dans%20l'UEMOA.pdf"
  },
  "rcpb": {
    "name": "Réseau des Caisses Populaires du Burkina — plaquette 2025",
    "url": "https://rcpb.bf/wp-content/uploads/2026/01/Plaquette_RCPB_VF_2025.pdf"
  },
  "bpbf": {
    "name": "Banque Postale du Burkina Faso — conditions publiées (2026)",
    "url": "https://www.banquepostale.bf/"
  },
  "coris-bank": {
    "name": "Coris Bank International (Burkina) — Conditions de banque CBI SA (PDF dated September 2026)",
    "url": "https://burkina.coris.bank/wp-content/uploads/2026/09/Conditions-de-Banque-CBI-SA-A4-Septembre-2026.pdf"
  },
  "la-poste-bf": {
    "name": "La Poste Burkina Faso — conditions des comptes d'épargne (2023)",
    "url": "https://laposte.bf/epargne-ordinaire/"
  },
  "iefp": {
    "name": "La finance pour tous (IEFP) — fiches et modules pédagogiques",
    "url": "https://www.lafinancepourtous.com"
  },
  "amf-fr": {
    "name": "AMF (France) — guides pour les épargnants : diversification, rendement et risque, horizon de placement, frais",
    "url": "https://www.amf-france.org/sites/institutionnel/files/pdf/71321/fr/Bien_diversifier_son_epargne_pour_atteindre_ses_objectifs.pdf"
  },
  "ecb": {
    "name": "European Central Bank — What is inflation? / Qu'est-ce que l'inflation ? (explainer, read 2026)",
    "url": "https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me-more/html/what_is_inflation.en.html"
  },
  "umoa-fgd-ceilings-2017": {
    "name": "UMOA Council of Ministers — Décision n°009 du 30/06/2017/CM/UMOA fixant les taux de contribution des adhérents au FGD-UMOA et les plafonds d'indemnisation (30 June 2017)",
    "url": "https://www.fgd-umoa.org/wp-content/uploads/2024/10/Decision-du-CM-relative-aux-taux-de-contribution-et-aux-plafonds-d-indemnistation-2-1.pdf"
  },
  "fgdr-umoa-circular-2022": {
    "name": "FGDR-UMOA — Circulaire n°005/2022/FGDR-UMOA relative aux modalités d'information des déposants, with annex form (14 January 2022)",
    "url": "https://www.fgd-umoa.org/wp-content/uploads/2024/09/circulaire-n_005-relative-aux-modalites-dinformation.pdf"
  },
  "fgdr-umoa-statutes-2018": {
    "name": "FGDR-UMOA — Statuts du Fonds de Garantie des Dépôts et de Résolution (2018)",
    "url": "https://www.fgd-umoa.org/wp-content/uploads/2024/09/Statuts-FGDR-UMOA-2018-1-min-compresse.pdf"
  },
  "umoa-banking-law": {
    "name": "BCEAO / Commission Bancaire de l'UMOA — Loi uniforme portant réglementation bancaire dans l'UMOA (model text, June 2023)",
    "url": "https://www.cb-umoa.org/sites/default/files/2026-08/Loi%20Bancaire%20UMOA.pdf"
  },
  "umoa-microfinance-law": {
    "name": "BCEAO / Commission Bancaire de l'UMOA — Loi uniforme portant réglementation de la microfinance dans l'UMOA (model text, PDF 2026)",
    "url": "https://www.cb-umoa.org/sites/default/files/2026-08/Loi%20microfinance%20UMOA.pdf"
  },
  "commission-bancaire": {
    "name": "Commission Bancaire de l'UMOA — rapport annuel 2025 ; Circulaire n°002-2020/CB/C sur les réclamations",
    "url": "https://www.cb-umoa.org/sites/default/files/RAPPORT%20ANNUEL%202025%20DE%20LA%20COMMISSION%20BANCAIRE.pdf"
  },
  "commission-bancaire-complaints-2020": {
    "name": "Commission Bancaire de l'UMOA — Circulaire n°002-2020/CB/C relative au traitement des réclamations des clients (in force 18 September 2020); online complaint form",
    "url": "https://www.cb-umoa.org/sites/default/files/2025-03/Circulaire%20N%C2%B0%20002-2020-CB-C%20relative%20au%20traitement%20des%20r%C3%A9clamations%20des%20clients_compressed.pdf"
  },
  "bceao-banking-landscape": {
    "name": "BCEAO — Paysage bancaire de l'UMOA, lists by country (at end December 2024)",
    "url": "https://www.bceao.int/fr/content/paysage-bancaire"
  },
  "bceao-inclusion-2024": {
    "name": "BCEAO — Rapport sur la situation de l'inclusion financière dans l'UEMOA au cours de l'année 2024 (March 2026)",
    "url": "https://www.bceao.int/sites/default/files/2026-06/Rapport_Annuel_Inclusion_Financiere_2024.pdf"
  },
  "bceao-sfd-indicators-2025": {
    "name": "BCEAO — Principaux indicateurs des SFD de l'UMOA au 30/09/2025 (22 January 2026)",
    "url": "https://www.bceao.int/sites/default/files/2026-02/Indicateurs%20au%2030%20septembre%202025.pdf"
  },
  "bceao-free-services-2014": {
    "name": "BCEAO — Instruction n°004-06-2014 relative aux services bancaires offerts à titre gratuit par les établissements de crédit de l'UMOA à leur clientèle (25 June 2014, in force 1 October 2014)",
    "url": "https://www.cb-umoa.org/sites/default/files/2022-01/INSTRUCTION%20N%C2%B0004-06-2014%20RELATIVE%20AUX%20SERVICES%20BANCAIRES%20OFFERTS%20%C3%80%20TITRE%20GRATUIT%20PAR%20LES%20%C3%89TABLISSEMENTS%20DE%20CR%C3%89DIT%20DE%20L%27UMOA%20%C3%80%20LEUR%20CLIENT%C3%88LE.pdf"
  },
  "bceao-emoney-2015": {
    "name": "BCEAO — Instruction n°008-05-2015 régissant les conditions et modalités d'exercice des activités des émetteurs de monnaie électronique dans l'UMOA (21 May 2015)",
    "url": "https://www.bceao.int/sites/default/files/2017-11/instruction_no008_05_2015_intranet.pdf"
  },
  "bceao-payment-services-2024": {
    "name": "BCEAO — Instruction n°001-01-2024 relative aux services de paiement dans l'UMOA (23 January 2024)",
    "url": "https://www.bceao.int/sites/default/files/2024-02/Instruction%20N%C2%B0001-01-2024%20relative%20aux%20services%20de%20paiement%20dans%20l%27UMOA%20%20ok.pdf"
  },
  "umoa-usury-2025": {
    "name": "Conseil des Ministres de l'UMOA — Décision n°19 du 29/12/2025 fixant le taux de l'usure",
    "url": "https://www.bceao.int/sites/default/files/2026-01/Decision-No19-du-29-12-2025_CMUMOA_fixant_le_taux_de_l-usure.pdf"
  },
  "fgdr-umoa-ceilings-2017": {
    "name": "UMOA Council of Ministers — Décision n°009 du 30/06/2017/CM/UMOA fixant les taux de contribution et les plafonds d'indemnisation du Fonds de Garantie des Dépôts dans l'UMOA (30 June 2017)",
    "url": "https://www.fgd-umoa.org/wp-content/uploads/2024/10/Decision-du-CM-relative-aux-taux-de-contribution-et-aux-plafonds-d-indemnistation-2-1.pdf"
  },
  "orange-bf": {
    "name": "Orange Burkina Faso — Grille tarifaire des transactions Orange Money (undated page, read 2026-10-03) and older page « Grille tarifaire Orange Money » still online",
    "url": "https://www.orange.bf/fr/tarifs-orange-money.html"
  },
  "moov-bf": {
    "name": "Moov Africa Burkina — Moov Money page (read 2026-10-03; no fee grid shown)",
    "url": "https://moov-africa.bf/moov-money2/"
  },
  "findex-data360": {
    "name": "World Bank — Global Findex Database, Data360 API, Burkina Faso, period 2024 (queried 2026-10-03)",
    "url": "https://data360api.worldbank.org/data360/data?DATABASE_ID=WB_FINDEX&REF_AREA=BFA&INDICATOR=WB_FINDEX_ACCOUNT_T_D"
  },
  "cgap-faq": {
    "name": "CGAP — Frequently Asked Questions about Financial Inclusion (page read 2026)",
    "url": "https://www.cgap.org/about-cgap/faq"
  },
  "fdic-msya": {
    "name": "FDIC — Money Smart for Young Adults, Module 1: Bank On It, Participant Guide (2022)",
    "url": "https://catalog.fdic.gov/catalog/sfc/servlet.shepherd/document/download/069t000000ghq1PAAQ"
  },
  "sidwaya-microfinance-law-2025": {
    "name": "Sidwaya (state daily, press) — reports on the adoption of the microfinance law on 13 February 2025 (loi n°001-2025/ALT as cited by the newspaper)",
    "url": "https://www.sidwaya.info/gestion-des-institutions-de-microfinance-une-loi-pour-reglementer-le-secteur/"
  },
  "oqsf-bf": {
    "name": "OQSF-BF (Observatoire de la qualité des services financiers) — d'après la presse (Sidwaya, AllAfrica)",
    "url": "https://fr.allafrica.com/stories/202511060327.html"
  },
  "bclcc": {
    "name": "BCLCC (Burkina cybercrime brigade) — alert on mobile-money scams, relayed by Wakat Séra (22 May 2026)",
    "url": "https://www.wakatsera.com/burkina-cybercriminalite-alerte-sur-les-arnaques-via-mobile-money/"
  },
  "creditinfo": {
    "name": "Creditinfo West Africa — Consommateurs: personne physique; contestations (read 2026)",
    "url": "https://creditinfo-uemoa.com/consommateurs/personne-physique/"
  },
  "cerise-sptf": {
    "name": "Cerise+SPTF — Annexe: Normes de Protection des Clients (2022)",
    "url": "https://spi-online.org/ressources?page_e31=46&file=files/ressources/CP%20Manuals/972%20CP%20Standards%20Manual_French.pdf"
  },
  "bceao": {
    "name": "BCEAO — listes des établissements agréés, situation de la microfinance, indicateurs d'inclusion financière",
    "url": "https://www.bceao.int/fr/content/etablissements-de-monnaie-electronique"
  },
  "yikri": {
    "name": "YIKRI — Méthodologie et conditions (2026)",
    "url": "https://www.yikri.org/conditions"
  },
  "baobab-bf": {
    "name": "Baobab Burkina Faso — Crédit entrepreneur, Crédit Taka (site, 2024)",
    "url": "https://baobab.com/bf/credit-entrepreneur/"
  },
  "banque-postale-bf": {
    "name": "Banque Postale du Burkina Faso — Prêt ordinaire, product sheet (site, 2024)",
    "url": "https://www.banquepostale.bf/"
  },
  "cima-code": {
    "name": "CIMA — Règlement n°0003/CIMA/PCMA/PCE/2012, Code des assurances, Livre VII Microassurance (2012)",
    "url": "https://fanaf.org/article_ressources/file/reglement_microassurance_CIMA_2012.pdf"
  },
  "amf-umoa": {
    "name": "AMF-UMOA — espace épargnant (guide, glossaire), vérification d'agrément, réclamations (Instruction n°50/2016), communiqués",
    "url": "https://www.amf-umoa.org/accueil/epargnant"
  },
  "koaci-police-2020": {
    "name": "Koaci — Burkina Faso : la police alerte sur des arnaques à travers les transferts d'argent (22 July 2020, press)",
    "url": "https://www.koaci.com/article/2020/07/22/burkina-faso/societe/burkina-faso-la-police-alerte-sur-des-arnaques-a-travers-les-transferts-dargent_143393.html"
  },
  "apanews-mef": {
    "name": "APA News — Burkina : mise en garde contre les placements financiers frauduleux (Ministry of Economy communiqué, press relay, date not captured)",
    "url": "https://fr.apanews.net/security/burkina-mise-en-garde-contre-les-placements-financiers-frauduleux/"
  },
  "wakatsera-esf-2024": {
    "name": "Wakat Séra — Education sociale et financière : de jeunes leaders et des journalistes outillés (29 March 2024, press)",
    "url": "https://www.wakatsera.com/education-sociale-et-financiere-de-jeunes-leaders-et-des-journalistes-outilles-sur-le-budget-et-lepargne/"
  },
  "bf-social-security-law-2021": {
    "name": "Assemblée nationale (Burkina Faso) — Loi n°004-2021/AN du 06 avril 2021 portant régime de sécurité sociale applicable aux travailleurs salariés et assimilés (2021)",
    "url": "https://www.assembleenationale.bf/storage/Loi/kh5PSt0jXMbbmdzEE89bH08kf5dw27KYt24h7EAa.pdf"
  },
  "bf-public-agents-law-2021": {
    "name": "Assemblée nationale (Burkina Faso) — Loi n°003-2021/AN du 1er avril 2021 portant régime de sécurité sociale applicable aux agents publics de l'État (2021)",
    "url": "https://www.assembleenationale.bf/storage/Loi/nVdn1BkjelHB5LKlIQkIRVmMprgjneWeYmeqBcEc.pdf"
  },
  "bf-cnss-rates-decree-2023": {
    "name": "Ministère de la Fonction publique, du Travail et de la Protection sociale (Burkina Faso) — Décret n°2023-0129/PRES-TRANS/PM/MFPTPS/MEFP fixant le taux d'appel des cotisations de sécurité sociale (24 February 2023, effect 30 August 2022)",
    "url": "https://www.fonction-publique.gov.bf/fileadmin/user_upload/storage/01_MARS_2023-_DECRET___N_2023___0129.pdf"
  },
  "bf-ramu-ministry-2024": {
    "name": "Ministère de la Fonction publique, du Travail et de la Protection sociale (Burkina Faso) — Bon à savoir: cotisations au régime d'assurance maladie universelle, summary of Décret n°2024-0345 (undated page, read 3 October 2026)",
    "url": "https://www.fonction-publique.gov.bf/accueil/actualites/details?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=2110&cHash=2e0d0ab8178b4741f7f2f3c0b9ee36e4"
  },
  "sidwaya-ramu-2024": {
    "name": "Sidwaya — Assurance maladie universelle: début des opérations d'affiliation et d'immatriculation, ministerial communiqué (29 October 2024)",
    "url": "https://www.sidwaya.info/assurance-maladie-universelle-debut-des-operations-daffiliation-et-dimmatriculation-sur-lensemble-du-territoire-communique/"
  },
  "sec-investor-gov": {
    "name": "US SEC, Investor.gov — Beginners' Guide to Asset Allocation, Diversification, and Rebalancing; Understanding Fees",
    "url": "https://www.investor.gov/additional-resources/general-resources/publications-research/info-sheets/beginners-guide-asset"
  },
  "brvm": {
    "name": "BRVM — Comment investir à la BRVM, règles de négociation, bulletin officiel de la cote",
    "url": "https://www.brvm.org/fr/comment-investir-la-brvm"
  },
  "dcbr": {
    "name": "DC/BR (Dépositaire Central/Banque de Règlement) — missions and news on the J+2 settlement cycle (in force since 4 December 2025)",
    "url": "https://dcbruemoa.org/"
  },
  "umoa-titres": {
    "name": "UMOA-Titres — Particuliers, FAQ, Glossaire, and the Burkina Treasury issue of 7 October 2026",
    "url": "https://www.umoatitres.org/fr/particuliers/"
  },
  "coris-bourse": {
    "name": "SGI Coris Bourse — pages pour les particuliers (lues le 3 octobre 2026)",
    "url": "https://coris-bourse.com/nos-services-produits/particuliers"
  },
  "sbif": {
    "name": "SGI SBIF (Burkina Faso) — Ouverture de compte, particuliers (undated page, read 2026-10-03)",
    "url": "https://www.sbifbourse.bf/phisiquement"
  },
  "africam": {
    "name": "Africa Asset Management, AFRICAM (Burkina Faso) — key information documents (DICI) of FCP Securitas, Expansio and Valoris (30 December 2022)",
    "url": "https://www.sbifbourse.bf/nos-fons"
  },
  "coris-asset": {
    "name": "Coris Asset Management (Burkina Faso) — Note d'information FCP Coris Actions (PDF, 2023) (document obtained 2026-10-03; the publisher's website carried injected links that day, so no link is given)"
  },
  "nsia-capital": {
    "name": "NSIA Capital (Côte d'Ivoire) — Grille tarifaire 2026, valid from 1 July 2026",
    "url": "https://nsiacapital.com/wp-content/uploads/2026/07/Grille-Tarifaire-NSIA-Capital-2026-Version-clientele-01072026-V2.pdf"
  },
  "cgi-bf": {
    "name": "Direction Générale des Impôts du Burkina Faso — Code général des impôts (éditions 2023 et 2024)",
    "url": "https://dgi.bf/verification/CGI"
  },
  "daba": {
    "name": "Daba Finance (app) — home page, FAQ and blog, company statements (read 2026-10-03)",
    "url": "https://dabafinance.com/fr"
  },
  "cgi-bf-2024": {
    "name": "Direction générale des impôts (Burkina Faso) — Code général des impôts, Version 2024 (online text, read 3 October 2026)",
    "url": "https://dgi.bf/verification/CGI"
  },
  "bf-finance-laws": {
    "name": "Assemblée législative de transition (Burkina Faso) — Loi n°042-2023/ALT (loi de finances 2024), Loi n°042-2024/ALT (loi de finances 2025); Government — Exposé des motifs du projet de loi de finances 2026 (hosted by DGI)",
    "url": "https://www.assembleenationale.bf/storage/Loi/FU4cnAqfHyREj0BsvgaPYtIa7qTRtT8piMrO4EIN.pdf"
  },
  "wikifin": {
    "name": "FSMA (Belgium), Wikifin — Investir petit à petit avec un plan d'investissement (21 April 2026); Comment gérer son portefeuille d'investissement ? (27 March 2026). Cite-only",
    "url": "https://www.wikifin.be/fr/epargner-et-investir/comment-investir-et-repartition-des-risques/comment-investir/investir-petit"
  },
  "mes-questions-dargent": {
    "name": "Banque de France, portail Mes questions d'argent — Quelques notions d'épargne avant d'investir (undated, read 2026-10-03). Cite-only",
    "url": "https://www.mesquestionsdargent.fr/epargne-et-placements/notions-epargne-avant-investir"
  },
  "ifi-bf": {
    "name": "Image Finances Internationales, SGI IFI (Burkina Faso) — product pages and brochure (September 2026, read 2026-10-03)",
    "url": "https://image-finance.com/"
  },
  "vie-publique": {
    "name": "Vie-publique.fr (DILA, France) — Qu'est-ce qu'un impôt ? (last modified 10 December 2025); Impôts directs et indirects; Impôt proportionnel et impôt progressif. Open licence: Licence Ouverte / Etalab 2.0",
    "url": "https://www.vie-publique.fr/fiches/21826-quest-ce-quun-impot-definition-de-limpot"
  },
  "economie-gouv-fr": {
    "name": "Ministère de l'Économie (France), economie.gouv.fr — Les impôts, de quoi parle-t-on ? (2024 data). Open licence: Licence Ouverte / Etalab 2.0",
    "url": "https://www.economie.gouv.fr/aqsmi/les-impots-de-quoi-parle-t"
  },
  "cra-canada": {
    "name": "Canada Revenue Agency — Learn about your taxes: Purpose of taxes, lesson Why you pay taxes (read 2026-10-03; non-commercial reproduction only)",
    "url": "https://www.canada.ca/en/revenue-agency/services/tax/individuals/educational-programs/purpose-taxes.html"
  },
  "bf-law-004-2021": {
    "name": "Burkina Faso — Loi n°004-2021/AN du 6 avril 2021 portant régime de sécurité sociale applicable aux travailleurs salariés et assimilés",
    "url": "https://www.assembleenationale.bf/storage/Loi/kh5PSt0jXMbbmdzEE89bH08kf5dw27KYt24h7EAa.pdf"
  },
  "bf-decree-2023-0129": {
    "name": "Burkina Faso — Décret n°2023-0129/PRES-TRANS/PM/MFPTPS/MEFP du 24 février 2023 fixant le taux d'appel des cotisations de sécurité sociale (effect from 30 August 2022)",
    "url": "https://www.fonction-publique.gov.bf/fileadmin/user_upload/storage/01_MARS_2023-_DECRET___N_2023___0129.pdf"
  },
  "bf-decree-2023-0132": {
    "name": "Burkina Faso — Décret n°2023-0132/PRES-TRANS/PM/MFPTPS/MEFP du 24 février 2023 fixant l'âge de départ à la retraite des travailleurs salariés et assimilés (effect from 30 August 2022)",
    "url": "https://www.fonction-publique.gov.bf/fileadmin/user_upload/storage/01_MARS_2023-DECRET__N_2023_0132.pdf"
  },
  "bf-law-003-2021": {
    "name": "Burkina Faso — Loi n°003-2021/AN du 1er avril 2021 portant régime de sécurité sociale applicable aux agents publics de l'État",
    "url": "https://www.assembleenationale.bf/storage/Loi/nVdn1BkjelHB5LKlIQkIRVmMprgjneWeYmeqBcEc.pdf"
  },
  "cipres": {
    "name": "CIPRES — Caisse nationale de sécurité sociale du Burkina Faso (profile page, read 2026-10-03)",
    "url": "https://lacipres.org/caisse-nationale-de-securite-sociale-du-burkina-faso/"
  },
  "mebf-cefore": {
    "name": "Maison de l'Entreprise du Burkina Faso, CEFORE — Formalités de création d'entreprises pour les personnes physiques (sheet dated 1 June 2026) and CEFORE page",
    "url": "https://www.me.bf/wp-content/uploads/2026/05/P1-Creation-Personne-Physique-010626.pdf"
  },
  "sidwaya": {
    "name": "Sidwaya — Rétro 2025, financements publics : les fonds nationaux passent de 14 à 4 (press, on the Council of Ministers of 20 November 2025)",
    "url": "https://www.sidwaya.info/retro-2025-financements-publics-les-fonds-nationaux-passent-de-14-a-4-pour-plus-defficacite/"
  }
};
